model:
  in_channels: 6  # 3 for positions + 3 for normals
  hidden_channels: 32  # Simple architecture with smaller hidden size
  num_transformer_layers: 1  # Further reduced from 2
  num_heads: 4  # Kept the same

training:
  batch_size: 4  # Further reduced batch size
  num_epochs: 100
  learning_rate: 1.0e-4
  weight_decay: 1.0e-5
  early_stopping_patience: 10
  checkpoint_dir: checkpoints
  device: cpu

data:
  raw_dir: data/raw
  processed_dir: data/processed
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

loss:
  topology_weight: 1.0
  normal_weight: 0.1
  uv_weight: 0.1
  feature_weight: 0.05

preprocessing:
  max_vertices: 10000
  normalize: true
  compute_normals: true
  compute_curvature: false
  detect_features: true 