model:
  in_channels: 3
  hidden_channels: 128
  num_transformer_layers: 4
  num_heads: 8

training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 1.0e-4
  weight_decay: 1.0e-5
  early_stopping_patience: 10
  checkpoint_dir: checkpoints
  device: cuda

data:
  raw_dir: data/raw
  processed_dir: data/processed
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

loss:
  topology_weight: 1.0
  normal_weight: 0.1
  uv_weight: 0.1
  feature_weight: 0.05

preprocessing:
  max_vertices: 10000
  normalize: true
  compute_normals: true
  compute_curvature: true
  detect_features: true 