# Mesh Processing Configuration

# General settings
general:
  seed: 42
  device: "cuda"  # or "cpu"
  debug: false

# Feature extraction settings
features:
  vertex_features:
    - "position"
    - "normal"
    - "curvature"
    - "laplacian"
  face_features:
    - "area"
    - "normal"
    - "centroid"

# Curvature computation settings
curvature:
  method: "cotangent"  # or "taubin"
  smoothing_iterations: 3
  smoothing_factor: 0.5

# Feature detection settings
feature_detection:
  sharp_edges:
    angle_threshold: 60  # degrees
  corners:
    angle_threshold: 30  # degrees
  creases:
    curvature_threshold: 0.1

# Dataset settings
dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  random_split: true

# Data loading settings
data:
  batch_size: 4
  num_workers: 4
  shuffle: true
  pin_memory: true

# Model settings
model:
  input_channels: 3  # number of input features
  hidden_channels: 64
  num_layers: 3
  dropout: 0.1
  activation: "relu"
  normalization: "batch"

# Training settings
training:
  learning_rate: 0.001
  weight_decay: 0.0001
  max_epochs: 100
  early_stopping_patience: 10
  gradient_clip_val: 1.0
  optimizer: "adam"
  scheduler: "reduce_on_plateau"
  scheduler_params:
    mode: "min"
    factor: 0.1
    patience: 5
    verbose: true 